# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qry_song.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 515)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(631, 491))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_001 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_001.sizePolicy().hasHeightForWidth())
        self.gb_001.setSizePolicy(sizePolicy)
        self.gb_001.setObjectName("gb_001")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_001)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hb_001 = QtWidgets.QHBoxLayout()
        self.hb_001.setObjectName("hb_001")
        self.lbl_sing002 = QtWidgets.QLabel(self.gb_001)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lbl_sing002.setFont(font)
        self.lbl_sing002.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_sing002.setObjectName("lbl_sing002")
        self.hb_001.addWidget(self.lbl_sing002)
        self.sing002 = QtWidgets.QLineEdit(self.gb_001)
        self.sing002.setObjectName("sing002")
        self.hb_001.addWidget(self.sing002)
        self.pb_sing002 = QtWidgets.QPushButton(self.gb_001)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pb_sing002.setFont(font)
        self.pb_sing002.setObjectName("pb_sing002")
        self.hb_001.addWidget(self.pb_sing002)
        self.verticalLayout_3.addLayout(self.hb_001)
        self.hb_002 = QtWidgets.QHBoxLayout()
        self.hb_002.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hb_002.setObjectName("hb_002")
        self.lbl_song002 = QtWidgets.QLabel(self.gb_001)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lbl_song002.setFont(font)
        self.lbl_song002.setObjectName("lbl_song002")
        self.hb_002.addWidget(self.lbl_song002)
        self.song002 = QtWidgets.QLineEdit(self.gb_001)
        self.song002.setObjectName("song002")
        self.hb_002.addWidget(self.song002)
        self.pb_song002 = QtWidgets.QPushButton(self.gb_001)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pb_song002.setFont(font)
        self.pb_song002.setObjectName("pb_song002")
        self.hb_002.addWidget(self.pb_song002)
        self.verticalLayout_3.addLayout(self.hb_002)
        self.horizontalLayout.addWidget(self.gb_001)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_exit.sizePolicy().hasHeightForWidth())
        self.pb_exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.pb_exit.setFont(font)
        self.pb_exit.setObjectName("pb_exit")
        self.horizontalLayout.addWidget(self.pb_exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tb_1 = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_1.sizePolicy().hasHeightForWidth())
        self.tb_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(10)
        self.tb_1.setFont(font)
        self.tb_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tb_1.setAutoScroll(True)
        self.tb_1.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tb_1.setDragEnabled(False)
        self.tb_1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tb_1.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tb_1.setRowCount(10)
        self.tb_1.setColumnCount(3)
        self.tb_1.setObjectName("tb_1")
        item = QtWidgets.QTableWidgetItem()
        self.tb_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tb_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tb_1.setItem(0, 1, item)
        self.tb_1.horizontalHeader().setVisible(True)
        self.tb_1.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_1.horizontalHeader().setDefaultSectionSize(100)
        self.tb_1.horizontalHeader().setMinimumSectionSize(50)
        self.remark = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.remark.setFont(font)
        self.remark.setObjectName("remark")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.lbl_sing002.setBuddy(self.sing002)
        self.lbl_song002.setBuddy(self.song002)

        self.retranslateUi(MainWindow)
        self.pb_exit.toggled['bool'].connect(self.tb_1.clear)
        self.pb_exit.clicked.connect(MainWindow.close)
        self.pb_sing002.clicked.connect(self.tb_1.clear)
        self.pb_song002.clicked.connect(self.tb_1.clear)
        self.pb_song002.toggled['bool'].connect(self.tb_1.clear)
        self.pb_sing002.toggled['bool'].connect(self.tb_1.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "卡拉OK歌曲查詢"))
        self.gb_001.setTitle(_translate("MainWindow", "查詢"))
        self.lbl_sing002.setText(_translate("MainWindow", "歌手名稱"))
        self.pb_sing002.setText(_translate("MainWindow", "搜尋"))
        self.lbl_song002.setText(_translate("MainWindow", "歌曲名稱"))
        self.pb_song002.setText(_translate("MainWindow", "搜尋"))
        self.pb_exit.setText(_translate("MainWindow", "離開"))
        self.tb_1.setSortingEnabled(True)
        item = self.tb_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.tb_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌曲名稱"))
        item = self.tb_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "曲號"))
        __sortingEnabled = self.tb_1.isSortingEnabled()
        self.tb_1.setSortingEnabled(False)
        self.tb_1.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

